# Generated by Django 6.0.3 on 2026-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='job_contract',
            field=models.FileField(blank=True, null=True, upload_to='documents/job/'),
        ),
    ]
