# Generated by Django 6.0.3 on 2026-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_contract_loanapplication_is_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='signed_contract',
            field=models.FileField(blank=True, null=True, upload_to='signed_contract/'),
        ),
    ]
