# Generated by Django 6.0.3 on 2026-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanpayment_payment_proof_loanpayment_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder_1_day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder_5_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder_due_today_sent',
            field=models.BooleanField(default=False),
        ),
    ]
