# Generated by Django 6.0.3 on 2026-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_overdue_notified_loan_reminder_1_day_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_penalty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
