# Generated by Django 6.0.3 on 2026-03-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_publicloanapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicloanapplication',
            name='loan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loantype'),
        ),
    ]
