# Generated by Django 6.0.3 on 2026-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_publicloanapplication_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicloanapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
