# Generated by Django 6.0.3 on 2026-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_publicloanapplication_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicloanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank/'),
        ),
        migrations.AddField(
            model_name='publicloanapplication',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id/'),
        ),
        migrations.AddField(
            model_name='publicloanapplication',
            name='job_contract',
            field=models.FileField(blank=True, null=True, upload_to='documents/job/'),
        ),
    ]
