# Generated by Django 6.0.3 on 2026-04-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_publicloanapplication_bank_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='parent_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reloans', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_payment', 'In Payment Period'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('paid', 'Paid Off'), ('reloaned', 'Reloaned')], default='active', max_length=20),
        ),
    ]
