# Generated by Django 6.0.3 on 2026-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_parent_loan_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='overdue_last_notified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
