# Generated by Django 6.0.3 on 2026-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_loan_overdue_last_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicloanapplication',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
