# Generated by Django 6.0.3 on 2026-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loanpayment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_payment', 'In Payment Period'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('paid', 'Paid Off'), ('reloaned', 'Reloaned'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
